package projectnetbeanssalim;

public class KonversiSuhu extends javax.swing.JFrame {
    
    /**
     * Creates new form FormSuhu
     */
    public KonversiSuhu() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        celsius1 = new javax.swing.JRadioButton();
        Fah1 = new javax.swing.JRadioButton();
        kelvin1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        celsius2 = new javax.swing.JRadioButton();
        fah2 = new javax.swing.JRadioButton();
        kelvin2 = new javax.swing.JRadioButton();
        Hitung = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Input");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("From");

        buttonGroup1.add(celsius1);
        celsius1.setText("Celsius");
        celsius1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celsius1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Fah1);
        Fah1.setText("Fahrenheit");
        Fah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fah1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(kelvin1);
        kelvin1.setText("Kelvin");
        kelvin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelvin1ActionPerformed(evt);
            }
        });

        jLabel3.setText("To");

        buttonGroup2.add(celsius2);
        celsius2.setText("Celsius");

        buttonGroup2.add(fah2);
        fah2.setText("Fahrenheit");

        buttonGroup2.add(kelvin2);
        kelvin2.setText("Kelvin");

        Hitung.setText("Calculate");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });

        jLabel4.setText("Result");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(celsius1)
                    .addComponent(jLabel2)
                    .addComponent(Fah1)
                    .addComponent(kelvin1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(celsius2)
                    .addComponent(jLabel3)
                    .addComponent(fah2)
                    .addComponent(kelvin2))
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(Hitung)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(celsius2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fah2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kelvin2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(celsius1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fah1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kelvin1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(Hitung)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
        double nilai;
        float hasil;
        String output;

        nilai=Double.valueOf(jTextField1.getText());
        if(celsius1.isSelected()){
            if(celsius2.isSelected()){
                hasil= (float) nilai;
                output=String.valueOf(hasil);
                jTextField2.setText(output);
            }
            if(fah2.isSelected()){
                hasil= (float) (nilai*1.8+32);
                output=String.valueOf(hasil);
                jTextField2.setText(output);
            }
            if(kelvin2.isSelected()){
                hasil= (float) (nilai+273.15);
                output=String.valueOf(hasil);
                jTextField2.setText(output);
            }

        }
        else if(Fah1.isSelected()){
            if(fah2.isSelected()){
                hasil= (float)nilai;
                output=String.valueOf(hasil);
                jTextField2.setText(output);
            }
            if(celsius2.isSelected()){
                hasil= (float) ((nilai-32)/1.8);
                output=String.valueOf(hasil);
                jTextField2.setText(output);
            }
            if(kelvin2.isSelected()){
                hasil= (float) ((nilai+459.67)/1.8);
                output=String.valueOf(hasil);
                jTextField2.setText(output);
            }
        }
        else if(kelvin1.isSelected()){
            if(kelvin2.isSelected()){
                hasil= (float)nilai;
                output=String.valueOf(hasil);
                jTextField2.setText(output);
            }
            if(celsius2.isSelected()){
                hasil= (float) (nilai-273.15);
                output=String.valueOf(hasil);
                jTextField2.setText(output);
            }
            if(fah2.isSelected()){
                hasil= (float) (nilai*1.8-459.67);
                output=String.valueOf(hasil);
                jTextField2.setText(output);
            }
        }
    }//GEN-LAST:event_HitungActionPerformed

    private void kelvin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelvin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelvin1ActionPerformed

    private void Fah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fah1ActionPerformed

    private void celsius1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celsius1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celsius1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Fah1;
    private javax.swing.JButton Hitung;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton celsius1;
    private javax.swing.JRadioButton celsius2;
    private javax.swing.JRadioButton fah2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton kelvin1;
    private javax.swing.JRadioButton kelvin2;
    // End of variables declaration//GEN-END:variables

}
